on: push
name: Continuous Integration
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [22.3]
        elixir: [1.10.2]

    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Cache dialyzer plts
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-plts

      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Deps get
        run: mix deps.get
      - name: Check Credo
        run: mix credo
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Compile with warnings
        run: mix do compile --warnings-as-errors
      - name: Dialyzer
        run: MIX_ENV=dev mix dialyzer
      - name: Set env.HEAD_TAG
        run: |
          echo "::set-env name=HEAD_TAG::$(git tag --points-at HEAD)"
          echo "env.HEAD_TAG: '$HEAD_TAG'"
      - name: Push Docker Images if New Tag ${{ env.HEAD_TAG }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login docker.pkg.github.com -u $DOCKER_USERNAME --password-stdin
          docker build -f Dockerfile \
                       -t docker.pkg.github.com/hez/elixir-cellar/elixir-cellar:$HEAD_TAG .
          docker push docker.pkg.github.com/hez/elixir-cellar/elixir-cellar:$HEAD_TAG
        if: env.HEAD_TAG != ''
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
