on: push
name: Continuous Integration
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [24.3.1]
        elixir: [1.13.3]

    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3

      - name: Cache dialyzer plts
        uses: actions/cache@v2
        with:
          path: priv/plts
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-plts

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Deps get
        run: mix deps.get
      - name: Check Credo
        run: mix credo
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Compile with warnings
        run: mix do compile --warnings-as-errors
      - name: Dialyzer
        run: mix dialyzer
